kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80 # Proxy
    protocol: TCP
  - containerPort: 30443
    hostPort: 443 # Proxy
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001 # Admin api
    protocol: TCP
  - containerPort: 30501
    hostPort: 30501 # Admin api
    protocol: TCP
  - containerPort: 30002
    hostPort: 30002 # Manager
    protocol: TCP
  - containerPort: 30500
    hostPort: 30500 # Manager
    protocol: TCP

    
    # kind create cluster --name yourClusterName --config=KinD.yaml
    #
    # We can leverage KIND’s extraPortMapping config option
    # when creating a cluster to forward ports from the host
    # to KIC/Gateway & for inter-host communication:
    # https://kind.sigs.k8s.io/docs/user/ingress/